import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isSignedIn ? (
          <>
            <p>Hello {user.username}.</p>
            <SignOutButton />
          </>
        ) : (
          <>
            <p>Not signed in.</p>
            <SignInButton />
          </>
        )}
      </main>
    </>
  );
};

export default Home;
