import { SignInButton, useUser } from "@clerk/nextjs";
import { type UserResource } from "@clerk/types";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";

const CreatePostWizard = (props: { user: UserResource }) => {
  const { user } = props;

  return (
    <div className="flex w-full items-center">
      <Image
        src={user.profileImageUrl}
        alt="Profile image"
        width={56}
        height={56}
        className="rounded-full"
      />
      <input
        placeholder="How's life today?"
        className="grow bg-transparent pl-3 outline-none"
      ></input>
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn, isLoaded, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-neutral-700 md:max-w-2xl">
          <div className="border-b border-neutral-700 p-4">
            {isLoaded ? (
              <>
                {isSignedIn ? (
                  <CreatePostWizard user={user} />
                ) : (
                  <>
                    <SignInButton />
                  </>
                )}
              </>
            ) : (
              <LoadingPage size={56} />
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
